### ISSUE TITLE
Colors for badge and circle for players differs

### ISSUE THREAD

**Issue by fen89** [freehuntx/gpn-mazing#8]
The badge and the color for players differs - shouldn't they be the same color for badge and circle for a player?

<img width="576" alt="image" src="https://user-images.githubusercontent.com/4036376/171867703-01735590-540a-4a39-ad83-5e1ec1157ef6.png">

We found out, that there is a `beginPath()` missing for the name box of the player, which will leads to this inconsitent behavior. 

I will submit a PR with the small fix.

**Comment by freehuntx** [comment]
Should be fixed by #9 
Thanks :)
